ktor:
    application:
        modules:
            - site.shaerware.printing.ApplicationKt.module
    deployment:
        port: 8060

store:
    api: "http://127.0.0.1:8090/api/v1"
    login: "printers"
    password: "printers"

host:
    id: "bcad9135-48e8-4b6d-b3f1-ed2b9dc64ba2"
    name: "Printing service"
